news/config/routes.rb
Rails.application.routes.draw do

  resources:newsinfos do
    resources :tasks,only: [:create,:destroy]
  end
    root'newsinfos#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

news/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

news/app/models/newsinfo.rb
class Newsinfo < ApplicationRecord
  has_many :tasks
  validates :title, presence: { message:"文字いれろよ" }
end

news/app/models/task.rb
class Task < ApplicationRecord
  belongs_to :newsinfo
end

news/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

news/app/controllers/newsinfos_controller.rb
class NewsinfosController < ApplicationController
  
  before_action :set_newsinfo, only:[:show, :destroy]

  def index
    @newsinfos = Newsinfo.all
  end

  def show
  end

  def new
  	@newsinfo = Newsinfo.new
  end

  def create
    @newsinfo = Newsinfo.new(newsinfo_params)
    if @newsinfo.save
    redirect_to newsinfos_path
    else
    	 render 'new'
    end
  end
  
   def destroy
     @newsinfo.destroy
     redirect_to newsinfos_path
   end

  private
  def newsinfo_params
    params[:newsinfo].permit(:title)
  end

  def set_newsinfo
    @newsinfo = Newsinfo.find(params[:id])
  end

end

news/app/controllers/tasks_controller.rb
class TasksController < ApplicationController
def create
  @newsinfo = Newsinfo.find(params[:newsinfo_id])
  @task = @newsinfo.tasks.create(task_params)
  redirect_to newsinfo_path(@newsinfo.id)
end   
private
  def task_params
    params[:task].permit(:title)
  end
end

news/app/helpers/application_helper.rb
module ApplicationHelper
end

news/app/helpers/newsinfos_helper.rb
module NewsinfosHelper
end

news/app/helpers/tasks_helper.rb
module TasksHelper
end

news/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>News</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <%= yield %>
    <%= link_to "HOME", newsinfos_path %>  
  </body>
</html>

news/app/views/newsinfos/index.html.erb
<div id = "all">
<div class = "title">
チャットとかのタイプのやつ
</div>

<div class = "creat">
<p><%= link_to "チャットルーム作成", new_newsinfo_path%></p>
</div>

<div class = "main">
<ul>
	<% @newsinfos.each do |newsinfo| %>
     <p>
       <%= link_to newsinfo.title, newsinfo_path(newsinfo.id) %>
       <%= link_to "ルーム削除", newsinfo_path(newsinfo.id), method: :delete, data: { confirm: "消すよ？" }%>
     </p>
	<% end %>
</ul>
</div>
</div>

news/app/views/newsinfos/new.html.erb
<h1>room name</h1>
  <%= form_for @newsinfo do |f| %>
    <p>
      <%= f.text_field :title %>
      <% if @newsinfo.errors.any?%>
      <%= @newsinfo.errors.messages[:title][0] %>
      <% end %>
    </p>
    <p>
      <%= f.submit %>
    </p>
  <% end %>

news/app/views/newsinfos/show.html.erb
<h1><%= @newsinfo.title %></h1>

  <ul>
    <% @newsinfo.tasks.each do |task|%>
    <li>
      <%= task.title %>
    </li>
  <% end %>
      

    <li>
      <%= form_for [@newsinfo, @newsinfo.tasks.build] do |f| %>
      <%= f.text_field :title %>
      <%= f.submit %>
      <% end %>    
    </li>
  </ul>